version: "3"
services:
  cita:
    image: cita/cita-run:ubuntu-18.04-20180813
    volumes:
      - ./cita:/opt/cita-run
      - ${LOCALTIME_PATH}:/etc/localtime
    container_name: cita_run
    working_dir: /opt/cita-run/cita/target/install
    stdin_open: true
    command: /opt/cita-run/create_main.sh
    env_file: .env
    ports:
        - "1337:1337"

  microscope:
    build:
      context: ./microscope
      dockerfile: ./Dockerfile
    tty: true
    depends_on:
      - re-birth
    ports:
      - "8080:80"
